# Generated by Django 4.2.7 on 2023-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='accessories/')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
