# Generated by Django 4.2.4 on 2023-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="create_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
