# Generated by Django 4.2.4 on 2023-11-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_slug_alter_product_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="products/"),
            preserve_default=False,
        ),
    ]
